### PR TITLE
Add installation instructions

### PR DESCRIPTION
**Pull request by tomdonaldson**
* Add installation instructions (00_SETUP.md)
* Update environment to astropy 4.0
* Update README
* Ignore downloads folder

### CODE REVIEW

**Review by stargaser — APPROVED** [review]
This all looks terrific to me!

I see some warnings in the SOLUTIONS-InspectingACandidateList.ipynb about taking log of negative numbers. Surely that's something new in astropy 4.0 visualization and it can be fixed separately.

**Comment by ceb8** [comment]
I'm seeing the same warnings as @stargaser.
I'm also getting an error in the CS_Catalog_Queries notebook. Specifically  in the cell after "4. TAP: Using the TAP to cross-correlate our objects with a catalog" I get a `DALFormatError: ValueError: 1:0: unclosed token`. I just confirmed that I don't get this in the old environment. 
I am heading shortly, but I can look into it more later. Are you also seeing this behavior @tomdonaldson ?

**Comment by tomdonaldson** [comment]
> I'm seeing the same warnings as @stargaser.
> I'm also getting an error in the CS_Catalog_Queries notebook. Specifically in the cell after "4. TAP: Using the TAP to cross-correlate our objects with a catalog" I get a `DALFormatError: ValueError: 1:0: unclosed token`. I just confirmed that I don't get this in the old environment.
> I am heading shortly, but I can look into it more later. Are you also seeing this behavior @tomdonaldson ?

Yes, I'll take a look.

**Comment by tomdonaldson** [comment]
The exception in the CS_Catalog_Queries notebook was caused by a missing data file needed for upload in a TAP query.  I've added the file to the repo.

**Comment by ceb8** [comment]
@tomdonaldson  Great!

**Review by ceb8 — APPROVED** [review]

**Pull request merged**
